version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 CoffeeShop.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=CoffeeShop.settings

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aziz123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
